### ISSUE TITLE
Add meta data to code

### ISSUE THREAD

**Issue by julirobicho** [wils3005/robicheau.ca#33]
**Meta Title (page title):**
Nicole Robicheau | Let's lead with humanity | Davenport, TO

**Meta Robots - add the ones that help index the site:**
_from https://ahrefs.com/blog/seo-meta-tags/:_
With that in mind, here are the values you can use in this tag:

index: tells bots to index the page;
noindex: tells bots not to index the page;
follow: tells bots to crawl links on the page, and that you also vouch for them;
nofollow: tells bots not to crawl links on the page, and that no endorsement is implied.
You can combine these in any of the following ways:

<meta name=”robots” content="noindex, nofollow">
<meta name=”robots” content="index, follow">
<meta name=”robots” content="noindex, follow">
<meta name=”robots” content="index, nofollow">

**Comment by wils3005** [comment]
Updated title (for University-Rosedale) and added an index/follow meta tag.
