### ISSUE TITLE
Update text in Why I'm Running

### ISSUE THREAD

**Issue by julirobicho** [wils3005/robicheau.ca#44]
**Update the 4th paragraph to:** 
My experiences have shown me that human well-being is fragile, and that’s inspired me to seek better solutions to the challenges we face in our local communities and around the globe. I’m determined to change the way decisions are made and that’s why I’m running to be your next Member of Parliament in University-Rosedale. Like you, I want meaningful change - now and for the future.

**Update the very last sentence to:**
Please join me and let’s put our hearts and souls into winning this riding, our community University-Rosedale.

**Comment by wils3005** [comment]
Done.
