### ISSUE TITLE
Update the favicon

### ISSUE THREAD

**Issue by julirobicho** [wils3005/robicheau.ca#45]
Not sure which size you need, let me know if you need something different.

![favicon-16x16](https://user-images.githubusercontent.com/77931359/130092270-63ee3d7f-ddb7-4b2d-9953-61cd506410a6.png)

![favicon-32x32](https://user-images.githubusercontent.com/77931359/130092272-a44c2b08-3193-4d3e-a1f5-f7d5f28c72b4.png)

**Comment by wils3005** [comment]
Done.
